export default [
  {
    id: 1,
    img: "../../public/bookcovers/d1.jpg",
    title: "Dune",
    value: "Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 629,
    year: 1965,
  },
  {
    id: 2,
    img: "../../public/bookcovers/d2.jpg",
    title: "Dune Messiah",
    value: "Dune Messiah",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 223,
    year: "",
  },
  {
    id: 3,
    img: "../../public/bookcovers/d3.jpg",
    title: "Children of Dune",
    value: "Children of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: "400",
    year: "",
  },
  {
    id: 4,
    img: "../../public/bookcovers/d4.jpg",
    title: "God Emperor of Dune",
    value: "God Emperor of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 577,
    year: "",
  },
  {
    id: 5,
    img: "../../public/bookcovers/d5.jpg",
    title: "Heretics of Dune",
    value: "Heretics of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 480,
    year: "",
  },
  {
    id: 6,
    img: "../../public/bookcovers/d6.jpg",
    title: "Chapterhouse Dune",
    value: "Chapterhouse Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 574,
    year: "",
  },
  {
    id: 7,
    img: "../../public/bookcovers/sapiens.jpg",
    title: "Sapiens",
    value: "Sapiens A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "History",
    pages: 331,
    year: "",
  },
  {
    id: 8,
    img: "../../public/bookcovers/deus.jpg",
    title: "Homo Deus",
    value: "Homo Deus A brief History of Tomorrow",
    author: "Yuval Noah Harari",
    genre: "History",
    pages: 333,
    year: "",
  },
  {
    id: 9,
    img: "../../public/bookcovers/thefinalempire.jpg",
    title: "The Final Empire",
    value: "The Final Empire",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 601,
    year: "",
  },
  {
    id: 10,
    img: "../../public/bookcovers/wellofascension.jpg",
    title: "The Well of Ascension",
    value: "The Well of Ascension",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 682,
    year: "",
  },
  {
    id: 11,
    img: "../../public/bookcovers/heroofages.jpg",
    title: "The Hero of Ages",
    value: "The Hero of Ages",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 630,
    year: "",
  },
  {
    id: 12,
    img: "../../public/bookcovers/secrethistorymistbirn.jpg",
    title: "Secret History",
    value: "Secret History",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 166,
    year: "",
  },
  {
    id: 13,
    img: "../../public/bookcovers/alloy of law.jpg",
    title: "The Alloy of Law",
    value: "The Alloy of Law",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 282,
    year: "",
  },
  {
    id: 14,
    img: "../../public/bookcovers/shadowsofself.jpg",
    title: "Shadows of Self",
    value: "Shadows of Self",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 346,
    year: "",
  },
  {
    id: 15,
    img: "../../public/bookcovers/thebandsofmourning.jpg",
    title: "The Bands of Mourning",
    value: "The Bands of Mourning",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 406,
    year: "",
  },
  {
    id: 16,
    img: "../../public/bookcovers/none.jpg",
    title: "And Then There Were None",
    value: "And then there were none",
    author: "Agatha Christie",
    genre: "Crime Thriller",
    pages: 204,
    year: "",
  },
  {
    id: 17,
    img: "../../s../../public/bookcovers/orient.jpg",
    title: "Murder on the Orient Express",
    value: "Murder on the Orient Express",
    author: "Agatha Christie",
    genre: "Crime Thriller",
    pages: 211,
    year: "",
  },
  {
    id: 18,
    img: "../../s../../public/bookcovers/mysterious.jpg",
    title: "The Mysterious Affair at Styles",
    value: "The Mysterious Affair at Styles",
    author: "Agatha Christie",
    genre: "Crime Thriller",
    pages: 178,
    year: "",
  },
  {
    id: 19,
    img: "../../public/bookcovers/metamorphosis.jpg",
    title: "The Metamorphosis",
    value: "The Metamorphosis",
    author: "Franz Kafka",
    genre: "Classics",
    pages: 34,
    year: 1915,
  },
  {
    id: 20,
    img: "../../public/bookcovers/the trail pengiun.jpg",
    title: "The Trail",
    value: "The Trail",
    author: "Franz Kafka",
    genre: "Classics",
    pages: 143,
    year: "",
  },
  {
    id: 21,
    img: "../../public/bookcovers/letters to his father.jpg",
    title: "Letter to His Father",
    value: "Letter to His Father",
    author: "Franz Kafka",
    genre: "Classics",
    pages: 63,
    year: "",
  },
  {
    id: 22,
    img: "../../public/bookcovers/the castle.jpg",
    title: "The Castle",
    value: "The Castle",
    author: "Franz Kafka",
    genre: "Classics",
    pages: 204,
    year: "",
  },
  {
    id: 23,
    img: "../../public/bookcovers/hamlet.jpg",
    title: "Hamlet",
    value: "Hamlet",
    author: "William Shakespeare",
    genre: "Play",
    pages: 168,
    year: "",
  },
  {
    id: 24,
    img: "../../public/bookcovers/macbeth.jpg",
    title: "Macbeth",
    value: "Macbeth",
    author: "William Shakespeare",
    genre: "Play",
    pages: 73,
    year: "",
  },
  {
    id: 25,
    img: "../../public/bookcovers/romeo.jpg",
    title: "Romeo & Juliet",
    value: "Romeo & Juliet",
    author: "William Shakespeare",
    genre: "Play",
    pages: 39,
    year: "",
  },
  {
    id: 26,
    img: "../../public/bookcovers/midsummer.jpg",
    title: "A Midsummer Night's Dream",
    value: "A Midsummer Night's Dream",
    author: "William Shakespeare",
    genre: "Play",
    pages: 96,
    year: "",
  },
  {
    id: 27,
    img: "../../public/bookcovers/othello.jpg",
    title: "Othello",
    value: "Othello",
    author: "William Shakespeare",
    genre: "Play",
    pages: 148,
    year: "",
  },
  {
    id: 28,
    img: "../../public/bookcovers/much ado.jpg",
    title: "Much Ado About Nothing",
    value: "Much Ado About Nothing",
    author: "William Shakespeare",
    genre: "Play",
    pages: 96,
    year: "",
  },
  {
    id: 29,
    img: "../../public/bookcovers/king lear.jpg",
    title: "King Lear",
    value: "King Lear",
    author: "William Shakespeare",
    genre: "Play",
    pages: 146,
    year: "",
  },
  {
    id: 30,
    img: "../../public/bookcovers/tempest.jpg",
    title: "The Tempest",
    value: "The Tempest",
    author: "William Shakespeare",
    genre: "Play",
    pages: 171,
    year: "",
  },
  {
    id: 31,
    img: "../../public/bookcovers/julius.jpg",
    title: "Julius Caesar",
    value: "Julius Caesar",
    author: "William Shakespeare",
    genre: "Play",
    pages: 110,
    year: "",
  },
  {
    id: 32,
    img: "../../public/bookcovers/whatif.jpg",
    title: "What if",
    value: "What if",
    author: "Randall Munroe",
    genre: "Science Humor",
    pages: 541,
    year: "",
  },
  {
    id: 33,
    img: "../../public/bookcovers/what if 2.jpg",
    title: "What if 2",
    value: "What if 2",
    author: "Randall Munroe",
    genre: "Science Humor",
    pages: 1239,
    year: "",
  },
  {
    id: 34,
    img: "../../public/bookcovers/dark matter.jpg",
    title: "Dark Matter",
    value: "Dark Matter",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 391,
    year: "",
  },
  {
    id: 35,
    img: "../../public/bookcovers/recursion yellow.jpg",
    title: "Recursion",
    value: "Recursion",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 460,
    year: "",
  },
  {
    id: 36,
    img: "../../public/bookcovers/upgrade.jpg",
    title: "Upgrade",
    value: "Upgrade",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 328,
    year: "",
  },
  {
    id: 37,
    img: "../../public/bookcovers/wp1.jpg",
    title: "Wayward Pines 1",
    value: "Wayward Pines 1",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 295,
    year: "",
  },
  {
    id: 38,
    img: "../../public/bookcovers/wp2.jpg",
    title: "Wayward Pines 2",
    value: "Wayward Pines 2",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 360,
    year: "",
  },
  {
    id: 39,
    img: "../../public/bookcovers/wp3.jpg",
    title: "Wayward Pines 3",
    value: "Wayward Pines 3",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 310,
    year: "",
  },
  {
    id: 40,
    img: "../../public/bookcovers/mars.jpg",
    title: "The Martian",
    value: "The Martian",
    author: "Andy Weir",
    genre: "Sci-fi",
    pages: 390,
    year: "",
  },
  {
    id: 41,
    img: "../../public/bookcovers/hail mary.jpg",
    title: "Project Hail Mary",
    value: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Sci-fi",
    pages: 440,
    year: "",
  },
  {
    id: 42,
    img: "../../public/bookcovers/artemis.jpg",
    title: "Artemis",
    value: "Artemis",
    author: "Andy Weir",
    genre: "Sci-fi",
    pages: 275,
    year: "",
  },
  {
    id: 43,
    img: "../../public/bookcovers/seven.jpg",
    title: "The Seven Husbands of Evelyn Hugo",
    value: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    pages: 377,
    year: "",
  },
  {
    id: 44,
    img: "../../public/bookcovers/daisy.jpg",
    title: "Daisy Jones & The Six",
    value: "Daisy Jones and The Six",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    pages: 261,
    year: "",
  },
  {
    id: 45,
    img: "../../public/bookcovers/one true.jpg",
    title: "One True Loves",
    value: "One True Loves",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    pages: 275,
    year: "",
  },
  {
    id: 46,
    img: "../../public/bookcovers/Evidence of the affair.jpg",
    title: "Evidence of the Affair",
    value: "Evidence of the Affair",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    pages: 76,
    year: "",
  },
  {
    id: 47,
    img: "../../public/bookcovers/maybe in another life.jpg",
    title: "Maybe in Another Life",
    value: "Maybe in Another Life",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    pages: 280,
    year: "",
  },
  {
    id: 48,
    img: "../../public/bookcovers/Forever interrupted.jpg",
    title: "Forever Interrupted",
    value: "Forever Interrupted",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    pages: 258,
    year: "",
  },
  {
    id: 49,
    img: "../../public/bookcovers/after i do.jpg",
    title: "After I Do",
    value: "After I Do",
    author: "Taylor Jenkins Reid",
    genre: "Fiction",
    pages: 279,
    year: "",
  },
];

// {
//     id:,
//     img: ,
//     title: "",
//     value: "",
//     author: "",
//     genre: "",
//     pages: ,
//     year: "",
//   },
