import dune from "../../public/bookcovers/d1.jpg";
import dunemessiah from "../../public/bookcovers/d2.jpg";
import childrenofdune from "../../public/bookcovers/d3.jpg";
import godemperorofdune from "../../public/bookcovers/d4.jpg";
import herecticsofdune from "../../public/bookcovers/d5.jpg";
import chapterhousedune from "../../public/bookcovers/d6.jpg";
import sapiens from "../../public/bookcovers/sapiens.jpg";
import deus from "../../public/bookcovers/deus.jpg";
import thefinal from "../../public/bookcovers/thefinalempire.jpg"
import wellofascension from "../../public/bookcovers/wellofascension.jpg"
import heroofages from "../../public/bookcovers/heroofages.jpg"
import secrethistorymist from "../../public/bookcovers/secrethistorymistbirn.jpg"
import alloylaw from "../../public/bookcovers/alloy of law.jpg"
import shadowsself from "../../public/bookcovers/shadowsofself.jpg"
import bandsmourning from "../../public/bookcovers/thebandsofmourning.jpg"
import none from "../../public/bookcovers/none.jpg";
import murder from "../../s../../public/bookcovers/orient.jpg";
import myst from "../../s../../public/bookcovers/mysterious.jpg";
import metamorph from "../../public/bookcovers/metamorphosis.jpg";
import trail from "../../public/bookcovers/the trail pengiun.jpg";
import letterstohisfather from "../../public/bookcovers/letters to his father.jpg";
import castle from "../../public/bookcovers/the castle.jpg";
import macbeth from "../../public/bookcovers/macbeth.jpg";
import romeo from "../../public/bookcovers/romeo.jpg";
import midsummer from "../../public/bookcovers/midsummer.jpg";
import muchado from "../../public/bookcovers/much ado.jpg";
import othello from "../../public/bookcovers/othello.jpg";
import kinglear from "../../public/bookcovers/king lear.jpg";
import tempest from "../../public/bookcovers/tempest.jpg";
import julius from "../../public/bookcovers/julius.jpg";
import hamlet from "../../public/bookcovers/hamlet.jpg";
import whatif from "../../public/bookcovers/whatif.jpg"
import whatif2 from "../../public/bookcovers/what if 2.jpg"
import darkmatter from "../../public/bookcovers/dark matter.jpg"
import recursion from "../../public/bookcovers/recursion yellow.jpg"
import upgrade from "../../public/bookcovers/upgrade.jpg"
import wp1 from "../../public/bookcovers/wp1.jpg"
import wp2 from "../../public/bookcovers/wp2.jpg"
import wp3 from "../../public/bookcovers/wp3.jpg"
import mars from "../../public/bookcovers/mars.jpg"
import hailmary from "../../public/bookcovers/hail mary.jpg"
import artemis from "../../public/bookcovers/artemis.jpg"




export default [
  {
    id: 1,
    img: dune,
    title: "Dune",
    value: "Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 629,
    year: 1965,
  },
  {
    id: 2,
    img: dunemessiah,
    title: "Dune Messiah",
    value: "Dune Messiah",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 223,
    year: "",
  },
  {
    id: 3,
    img: childrenofdune,
    title: "Children of Dune",
    value: "Children of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: "400",
    year: "",
  },
  {
    id: 4,
    img: godemperorofdune,
    title: "God Emperor of Dune",
    value: "God Emperor of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 577,
    year: "",
  },
  {
    id: 5,
    img: herecticsofdune,
    title: "Heretics of Dune",
    value: "Heretics of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 480,
    year: "",
  },
  {
    id: 6,
    img: chapterhousedune,
    title: "Chapterhouse Dune",
    value: "Chapterhouse Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 574,
    year: "",
  },
  {
    id: 7,
    img: sapiens,
    title: "Sapiens",
    value: "Sapiens A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "History",
    pages: 331,
    year: "",
  },
  {
    id: 8,
    img: deus,
    title: "Homo Deus",
    value: "Homo Deus A brief History of Tomorrow",
    author: "Yuval Noah Harari",
    genre: "History",
    pages: 333,
    year: "",
  },
  {
    id:9,
    img: thefinal,
    title: "The Final Empire",
    value: "The Final Empire",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 601,    
    year: "",
  },
{
    id:10,
    img: wellofascension,
    title: "The Well of Ascension",
    value: "The Well of Ascension",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 682,
    year: "",
  },
{
    id:11,
    img: heroofages,
    title: "The Hero of Ages",
    value: "The Hero of Ages",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 630,
    year: "",
  },
{
    id:12,
    img: secrethistorymist,
    title: "Secret History",
    value: "Secret History",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 166,
    year: "",
  },
{
    id:13,
    img: alloylaw,
    title: "The Alloy of Law",
    value: "The Alloy of Law",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 282,
    year: "",
  },
{
    id:14,
    img: shadowsself,
    title: "Shadows of Self",
    value: "Shadows of Self",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 346,
    year: "",
  },
{
    id:15,
    img: bandsmourning,
    title: "The Bands of Mourning",
    value: "The Bands of Mourning",
    author: "Brandon Sanderson",
    genre: "Fantasy Fiction",
    pages: 406,
    year: "",
  },
  {
    id: 16,
    img: none,
    title: "And Then There Were None",
    value: "And then there were none",
    author:"Agatha Christie",
    genre:"Crime Thriller",
    pages: 204,
    year: "",
  },
  {
    id: 17,
    img: murder,
    title: "Murder on the Orient Express",
    value: "Murder on the Orient Express",
    author:"Agatha Christie",
    genre:"Crime Thriller",
    pages: 211,
    year: "",
  },
  {
    id: 18,
    img: myst,
    title: "The Mysterious Affair at Styles",
    value: "The Mysterious Affair at Styles",
    author:"Agatha Christie",
    genre:"Crime Thriller",
    pages: 178,
    year: "",
  },
  {
    id: 19,
    img: metamorph,
    title: "The Metamorphosis",
    value: "The Metamorphosis",
    author:"Franz Kafka",
    genre:"Classics",
    pages: 34,
    year: 1915,
  },
  {
    id: 20,
    img: trail,
    title: "The Trail",
    value: "The Trail",
    author:"Franz Kafka",
    genre:"Classics",
    pages: 143,
    year: "",
  },
  {
    id: 21,
    img: letterstohisfather,
    title: "Letter to His Father",
    value: "Letter to His Father",
    author:"Franz Kafka",
    genre:"Classics",
    pages: 63,
    year: "",
  },
  {
    id: 22,
    img: castle,
    title: "The Castle",
    value: "The Castle",
    author:"Franz Kafka",
    genre:"Classics",
    pages: 204,
    year: "",
  },
  {
    id: 23,
    img: hamlet,
    title: "Hamlet",
    value: "Hamlet",
    author:"William Shakespeare",
    genre:"Play",
    pages: 168,
    year: "",
  },
  {
    id: 24,
    img: macbeth,
    title: "Macbeth",
    value: "Macbeth",
    author:"William Shakespeare",
    genre:"Play",
    pages: 73,
    year: "",
  },
  {
    id: 25,
    img: romeo,
    title: "Romeo & Juliet",
    value: "Romeo & Juliet",
    author:"William Shakespeare",
    genre:"Play",
    pages: 39,
    year: "",
  },
  {
    id: 26,
    img: midsummer,
    title: "A Midsummer Night's Dream",
    value: "A Midsummer Night's Dream",
    author:"William Shakespeare",
    genre:"Play",
    pages: 96,
    year: "",
  },
  {
    id: 27,
    img: othello,
    title: "Othello",
    value: "Othello",
    author:"William Shakespeare",
    genre:"Play",
    pages: 148,
    year: "",
  },
  {
    id: 28,
    img: muchado,
    title: "Much Ado About Nothing",
    value: "Much Ado About Nothing",
    author:"William Shakespeare",
    genre:"Play",
    pages: 96,
    year: "",
  },
  {
    id: 29,
    img: kinglear,
    title: "King Lear",
    value: "King Lear",
    author:"William Shakespeare",
    genre:"Play",
    pages: 146,
    year: "",
  },
  {
    id: 30,
    img: tempest,
    title: "The Tempest",
    value: "The Tempest",
    author:"William Shakespeare",
    genre:"Play",
    pages: 171,
    year: "",
  },
  {
    id: 31,
    img: julius,
    title: "Julius Caesar",
    value: "Julius Caesar",
    author:"William Shakespeare",
    genre:"Play",
    pages: 110,
    year: "",
  },
  {
    id: 32,
    img: whatif,
    title: "What if",
    value: "What if",
    author:"Randall Munroe",
    genre:"Science Humor",
    pages: 541,
    year: "",
  },
  {
    id: 33,
    img: whatif2,
    title: "What if 2",
    value: "What if 2",
    author:"Randall Munroe",
    genre:"Science Humor",
    pages: 1239,
    year: "",
  },
  {
    id: 34,
    img: darkmatter,
    title: "Dark Matter",
    value: "Dark Matter",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 391,
    year: "",
  },
  {
    id: 35,
    img: recursion,
    title: "Recursion",
    value: "Recursion",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 460,
    year: "",
  },
  {
    id: 36,
    img: upgrade,
    title: "Upgrade",
    value: "Upgrade",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 328,
    year: "",
  },
  {
    id: 37,
    img: wp1,
    title: "Wayward Pines 1",
    value: "Wayward Pines 1",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 295,
    year: "",
  },
  {
    id: 38,
    img: wp2,
    title: "Wayward Pines 2",
    value: "Wayward Pines 2",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 360,
    year: "",
  },
  {
    id: 39,
    img: wp3,
    title: "Wayward Pines 3",
    value: "Wayward Pines 3",
    author: "Blake Crouch",
    genre: "Sci-fi",
    pages: 310,
    year: "",
  },
  {
    id: 40,
    img: mars,
    title: "The Martian",
    value: "The Martian",
    author: "Andy Weir",
    genre: "Sci-fi",
    pages: 390,
    year: "",
  },
  {
    id: 41,
    img: hailmary,
    title: "Project Hail Mary",
    value: "Project Hail Mary",
    author: "Andy Weir",
    genre: "Sci-fi",
    pages: 440,
    year: "",
  },
  {
    id: 42,
    img: artemis,
    title: "Artemis",
    value: "Artemis",
    author: "Andy Weir",
    genre: "Sci-fi",
    pages: 275,
    year: "",
  },
];

// {
//     id:,
//     img: ,
//     title: "",
//     value: "",
//     author: "",
//     genre: "",
//     pages: ,
//     year: "",
//   },
