import dune from "../images/d1.jpg";
import dunemessiah from "../images/d2.jpg";
import childrenofdune from "../images/d3.jpg";
import godemperorofdune from "../images/d4.jpg";
import herecticsofdune from "../images/d5.jpg";
import chapterhousedune from "../images/d6.jpg";
import sapiens from "../images/sapiens.jpg";
import deus from "../images/deus.jpg";

export default [
  {
    id: 1,
    img: dune,
    title: "Dune",
    value: "Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 629,
    year: 1965,
  },
  {
    id: 2,
    img: dunemessiah,
    title: "Dune Messiah",
    value: "Dune Messiah",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 223,
    year: "",
  },
  {
    id: 3,
    img: childrenofdune,
    title: "Children of Dune",
    value: "Children of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: "400",
    year: "",
  },
  {
    id: 4,
    img: godemperorofdune,
    title: "God Emperor of Dune",
    value: "God Emperor of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 577,
    year: "",
  },
  {
    id: 5,
    img: herecticsofdune,
    title: "Heretics of Dune",
    value: "Heretics of Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 480,
    year: "",
  },
  {
    id: 6,
    img: chapterhousedune,
    title: "Chapterhouse Dune",
    value: "Chapterhouse Dune",
    author: "Frank Herbert",
    genre: "Sci-fi",
    pages: 574,
    year: "",
  },
  {
    id: 7,
    img: sapiens,
    title: "Sapiens",
    value: "Sapiens A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "History",
    pages: 331,
    year: "",
  },
  {
    id: 8,
    img: deus,
    title: "Homo Deus",
    value: "Homo Deus A brief History of Tomorrow",
    author: "Yuval Noah Harari",
    genre: "History",
    pages: 333,
    year: "",
  },
  {
    id:9,
    img: "",
    title: "The Final Empire",
    value: "The Final Empire",
    author: "Brandon Sanderson",
    genre: "",
    pages: "",
    year: "",
  },
{
    id:10,
    img: "",
    title: "The Well of Ascension",
    value: "The Well of Ascension",
    author: "Brandon Sanderson",
    genre: "",
    pages: "",
    year: "",
  },
{
    id:11,
    img: "",
    title: "The Hero of Ages",
    value: "The Hero of Ages",
    author: "Brandon Sanderson",
    genre: "",
    pages: "",
    year: "",
  },
{
    id:12,
    img: "",
    title: "Secret History",
    value: "Secret History",
    author: "Brandon Sanderson",
    genre: "",
    pages: "",
    year: "",
  },
{
    id:13,
    img: "",
    title: "The Alloy of Law",
    value: "The Alloy of Law",
    author: "Brandon Sanderson",
    genre: "",
    pages: "",
    year: "",
  },
{
    id:14,
    img: "",
    title: "Shadows of Self",
    value: "Shadows of Self",
    author: "Brandon Sanderson",
    genre: "",
    pages: "",
    year: "",
  },
{
    id:15,
    img: "",
    title: "The Bands of Mourning",
    value: "The Bands of Mourning",
    author: "Brandon Sanderson",
    genre: "",
    pages: "",
    year: "",
  },
];

// {
//     id:,
//     img: ,
//     title: "",
//     value: "",
//     author: "",
//     genre: "",
//     pages: ,
//     year: "",
//   },
